### ISSUE TITLE
Svelte Component not working for bookshop?

### ISSUE THREAD

**Issue by KevinFPhan** [CloudCannon/astro-starter#2]
I import a Svelte component as a bookshop component but got this error `src/shared/astro/page.astro:1:1294: error: No loader is configured for ".svelte" files: src/components/navigation/header.svelte at failureErrorWithLog`
And I added this `const componentImports = import.meta.glob('../../components/**/*.{jsx,astro,svelte}', {
  eager: true,
});`

But I can import a Svelte Component as a regular component outside of bookshop components directory.

**Comment by remifreriks** [comment]
@KevinFPhan I'm looking at using Cloudcannon. We are currently working with svelte. Cloudcannon bookshop only works with last year's svelte 3. This is why I am looking at the Astro implementation because svelte is not actively supported. In the meantime, do you have any svelte components working? Because our team is used to svelte, this will make the transition a lot easier.

**Comment by tomrcc** [comment]
Hi @KevinFPhan,

Apologies for the slow reply!
We do not support .svelte components in Astro Bookshop unfortunately.
At the moment we only support .astro and .jsx components.

However, we can use the [svelte-connector](https://cloudcannon.com/documentation/articles/live-editing-with-svelte/) to enable a similar experience to Bookshop - where we get to see components update live in our Visual Editor, through changes to front matter that we control in CloudCannon's user interface.

Thanks,
Tom

**Comment by tomrcc** [comment]
Hi @remi-freriks 

We have updated our [Sveltekit Sendit template](https://github.com/CloudCannon/sendit-sveltekit-template) to use Svelte 4, and it seems to work as normal.
Hopefully that frees up your team to keep working in Svelte!
Like I mentioned above, we also have a svelte-connector available as well if you wanted to implement your own custom solution.

Best wishes,
Tom
